version: '3.8'

services:
  nginx:
    build:
      context: ./
      dockerfile: DockerfileNginx
    ports:
      - "80:80"
    depends_on:
      web:
        condition: service_healthy
      flower:
        condition: service_started
    volumes:
      - ./media:/media
      - ./static:/static
    networks:
      - net

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${SQL_DATABASE_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_PORT=${SQL_PORT}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE_NAME} -h localhost" ]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - net

  redis:
    image: redis:alpine
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - net
      
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DEV=${DEV}
      - SITE_ID=${SITE_ID}
      - SQL_HOST=${SQL_HOST}
      - MAIN_DOMAIN=${MAIN_DOMAIN}
      - HTTPS=${HTTPS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE_NAME=${SQL_DATABASE_NAME}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_PORT=${SQL_PORT}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - TZ=${TZ}
    volumes:
      - ./:/srv
      - ./media:/srv/media
      - ./static:/srv/static
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: [ "CMD", "sh", "-c", "netcat -z 0.0.0.0 8000 || exit 1" ]
      interval: 5s
      timeout: 2s
      retries: 10
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - net


  worker:
    build:
      context: .
      dockerfile: DockerfileCeleryWorker
    hostname: worker
    entrypoint: celery
    command: -A config worker --loglevel=warning
    volumes:
      - ./:/srv
      - ./media:/srv/media
      - ./static:/srv/static
    links:
      - redis
    environment:
      - POSTGRES_DB=${SQL_DATABASE_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_PORT=${SQL_PORT}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - TZ=${TZ}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_healthy
    networks:
      - net

  flower:
    image: mher/flower
    hostname: flower
    command: celery -A celery flower --loglevel=warning --url-prefix=flower --basic_auth=${FLOWER_DEFAULT_USER}:${FLOWER_DEFAULT_PASS}
    environment:
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - TZ=${TZ}
    ports:
      - "5555:5555"
    volumes:
      - ./:/srv
      - ./media:/srv/media
      - ./static:/srv/static
    links:
      - redis
    depends_on:
      web:
        condition: service_healthy
      worker:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - net

  celerybeat:
    build:
      context: .
    hostname: celerybeat
    entrypoint: celery
    command: -A config beat --loglevel=warning --schedule=/srv/celerybeat-schedule --pidfile=/srv/celerybeat.pid
    volumes:
      - ./:/srv
      - ./media:/srv/media
      - ./static:/srv/static
    depends_on:
      web:
        condition: service_healthy
      worker:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - TZ=${TZ}
    networks:
      - net



networks:
  net:
    driver: bridge