version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    environment:
      # Устанавливаем переменные приложения Django
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DEV=${DEV}
      - SITE_ID=${SITE_ID}
      - SQL_HOST=${SQL_HOST}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE_NAME=${SQL_DATABASE_NAME}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_PORT=${SQL_PORT}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    volumes:
      - ./:/usr/src/app/
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"


  postgres:
    image: postgres
    restart: always
    environment:
      # Require naming
      - POSTGRES_DB=${SQL_DATABASE_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_PORT=${SQL_PORT}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE_NAME} -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  media_volume: